/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd_aula09_geral.view;

import sd_aula09_light.controller.Light;

/**
 *
 * @author abdiel.cordeiro
 */
public class CasaFrame extends javax.swing.JFrame {

    private Light luzController = new Light();

    /**
     * Creates new form CasaFrame
     */
    public CasaFrame() {
        initComponents();
        jPanelRaiz.setVisible(false);

        jPanelLuz.setVisible(false);
        jPanelAquecedor.setVisible(false);
        jPanelAr.setVisible(false);
        jPanelPorta.setVisible(false);
        jPanelTv.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aquecedorAgua = new javax.swing.JButton();
        luz = new javax.swing.JButton();
        arCondicionado = new javax.swing.JButton();
        porta = new javax.swing.JButton();
        televisao = new javax.swing.JButton();
        jPanelRaiz = new javax.swing.JPanel();
        jPanelPorta = new javax.swing.JPanel();
        labelLigadoDesligadoLuz10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanelTv = new javax.swing.JPanel();
        bntLigarDesligarLuz8 = new javax.swing.JToggleButton();
        intensidadeLuz8 = new javax.swing.JToggleButton();
        inputIntensidadeLuz9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanelAquecedor = new javax.swing.JPanel();
        bntLigarDesligarLuz9 = new javax.swing.JToggleButton();
        intensidadeLuz9 = new javax.swing.JToggleButton();
        inputIntensidadeLuz10 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanelLuz = new javax.swing.JPanel();
        bntLigarDesligarLuz10 = new javax.swing.JToggleButton();
        intensidadeLuz10 = new javax.swing.JToggleButton();
        inputIntensidadeLuz4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanelAr = new javax.swing.JPanel();
        bntLigarDesligarLuz11 = new javax.swing.JToggleButton();
        intensidadeLuz11 = new javax.swing.JToggleButton();
        jLabel28 = new javax.swing.JLabel();
        inputIntensidadeLuz11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem-Vindo a Smart Home");

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Qual equipamento deseja Controlar ? ");

        aquecedorAgua.setBackground(new java.awt.Color(0, 204, 255));
        aquecedorAgua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aquecedorAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/water-heater.png"))); // NOI18N
        aquecedorAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aquecedorAguaActionPerformed(evt);
            }
        });

        luz.setBackground(new java.awt.Color(0, 204, 255));
        luz.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        luz.setIcon(new javax.swing.ImageIcon("C:\\Users\\abdiel.cordeiro\\Documents\\NetBeansProjects\\projetoA1\\SD_Aula09_Control\\src\\sd_aula09_assets\\Imagem\\smart-light.png")); // NOI18N
        luz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzActionPerformed(evt);
            }
        });

        arCondicionado.setBackground(new java.awt.Color(0, 204, 255));
        arCondicionado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        arCondicionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/air-conditioner.png"))); // NOI18N
        arCondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arCondicionadoActionPerformed(evt);
            }
        });

        porta.setBackground(new java.awt.Color(0, 204, 255));
        porta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        porta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/knob.png"))); // NOI18N
        porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaActionPerformed(evt);
            }
        });

        televisao.setBackground(new java.awt.Color(0, 204, 255));
        televisao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        televisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/smart-tv.png"))); // NOI18N
        televisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisaoActionPerformed(evt);
            }
        });

        labelLigadoDesligadoLuz10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLigadoDesligadoLuz10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLigadoDesligadoLuz10.setText("Fechada");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/knob.png"))); // NOI18N

        jButton5.setText("Enviar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPortaLayout = new javax.swing.GroupLayout(jPanelPorta);
        jPanelPorta.setLayout(jPanelPortaLayout);
        jPanelPortaLayout.setHorizontalGroup(
            jPanelPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortaLayout.createSequentialGroup()
                .addGroup(jPanelPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPortaLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel22))
                    .addGroup(jPanelPortaLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(labelLigadoDesligadoLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPortaLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanelPortaLayout.setVerticalGroup(
            jPanelPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPortaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(labelLigadoDesligadoLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanelPortaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        bntLigarDesligarLuz8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntLigarDesligarLuz8.setText("LIGAR");

        intensidadeLuz8.setText("Alterar Canal");
        intensidadeLuz8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidadeLuz8ActionPerformed(evt);
            }
        });

        inputIntensidadeLuz9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIntensidadeLuz9ActionPerformed(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/television.png"))); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/add.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/minus.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Voume");

        javax.swing.GroupLayout jPanelTvLayout = new javax.swing.GroupLayout(jPanelTv);
        jPanelTv.setLayout(jPanelTvLayout);
        jPanelTvLayout.setHorizontalGroup(
            jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTvLayout.createSequentialGroup()
                .addGroup(jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTvLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntLigarDesligarLuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanelTvLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTvLayout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTvLayout.createSequentialGroup()
                                .addComponent(inputIntensidadeLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(intensidadeLuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanelTvLayout.setVerticalGroup(
            jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTvLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntLigarDesligarLuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIntensidadeLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intensidadeLuz8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35))
        );

        bntLigarDesligarLuz9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntLigarDesligarLuz9.setText("LIGAR");

        intensidadeLuz9.setText("Alterar Intensidade");
        intensidadeLuz9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidadeLuz9ActionPerformed(evt);
            }
        });

        inputIntensidadeLuz10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIntensidadeLuz10ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/air-conditioner.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAquecedorLayout = new javax.swing.GroupLayout(jPanelAquecedor);
        jPanelAquecedor.setLayout(jPanelAquecedorLayout);
        jPanelAquecedorLayout.setHorizontalGroup(
            jPanelAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAquecedorLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(inputIntensidadeLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(intensidadeLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanelAquecedorLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addGroup(jPanelAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntLigarDesligarLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAquecedorLayout.setVerticalGroup(
            jPanelAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAquecedorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel27)
                .addGap(33, 33, 33)
                .addComponent(bntLigarDesligarLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelAquecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIntensidadeLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intensidadeLuz9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanelLuz.setPreferredSize(new java.awt.Dimension(803, 296));

        bntLigarDesligarLuz10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntLigarDesligarLuz10.setText("LIGAR");

        intensidadeLuz10.setText("Alterar Intensidade");
        intensidadeLuz10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidadeLuz10ActionPerformed(evt);
            }
        });

        inputIntensidadeLuz4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIntensidadeLuz4ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/smart-light.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLuzLayout = new javax.swing.GroupLayout(jPanelLuz);
        jPanelLuz.setLayout(jPanelLuzLayout);
        jPanelLuzLayout.setHorizontalGroup(
            jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzLayout.createSequentialGroup()
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLuzLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(inputIntensidadeLuz4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(intensidadeLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLuzLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntLigarDesligarLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(43, 43, 43))
        );
        jPanelLuzLayout.setVerticalGroup(
            jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLuzLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(bntLigarDesligarLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelLuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIntensidadeLuz4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intensidadeLuz10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        bntLigarDesligarLuz11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntLigarDesligarLuz11.setText("LIGAR");

        intensidadeLuz11.setText("Alterar Temperatura");
        intensidadeLuz11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidadeLuz11ActionPerformed(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd_aula09_assets/Imagem/air-conditioner.png"))); // NOI18N

        inputIntensidadeLuz11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIntensidadeLuz11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelArLayout = new javax.swing.GroupLayout(jPanelAr);
        jPanelAr.setLayout(jPanelArLayout);
        jPanelArLayout.setHorizontalGroup(
            jPanelArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArLayout.createSequentialGroup()
                .addGap(78, 227, Short.MAX_VALUE)
                .addComponent(inputIntensidadeLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(intensidadeLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanelArLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(jPanelArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntLigarDesligarLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArLayout.setVerticalGroup(
            jPanelArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(bntLigarDesligarLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intensidadeLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputIntensidadeLuz11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jPanelRaizLayout = new javax.swing.GroupLayout(jPanelRaiz);
        jPanelRaiz.setLayout(jPanelRaizLayout);
        jPanelRaizLayout.setHorizontalGroup(
            jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelRaizLayout.setVerticalGroup(
            jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAquecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelLuz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanelRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRaizLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHomeLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(luz, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelHomeLayout.createSequentialGroup()
                                    .addComponent(arCondicionado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(porta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(televisao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(aquecedorAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelHomeLayout.createSequentialGroup()
                            .addGap(231, 231, 231)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luz)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porta)
                            .addComponent(arCondicionado)
                            .addComponent(televisao)
                            .addComponent(aquecedorAgua))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void televisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisaoActionPerformed
        if (jPanelRaiz.isVisible() == false) {
            jPanelRaiz.setVisible(true);
            jPanelTv.setVisible(true);
        } else {
            jPanelRaiz.setVisible(false);
            jPanelTv.setVisible(false);
        }
    }//GEN-LAST:event_televisaoActionPerformed

    private void portaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaActionPerformed
        if (jPanelRaiz.isVisible() == false) {
            jPanelRaiz.setVisible(true);
            jPanelPorta.setVisible(true);
        } else {
            jPanelRaiz.setVisible(false);
            jPanelPorta.setVisible(false);
        }
    }//GEN-LAST:event_portaActionPerformed

    private void arCondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arCondicionadoActionPerformed
        if (jPanelRaiz.isVisible() == false) {
            jPanelRaiz.setVisible(true);
            jPanelAr.setVisible(true);
        } else {
            jPanelRaiz.setVisible(false);
            jPanelAr.setVisible(false);
        }
    }//GEN-LAST:event_arCondicionadoActionPerformed

    private void luzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzActionPerformed
        if (jPanelRaiz.isVisible() == false) {
            jPanelRaiz.setVisible(true);
            jPanelLuz.setVisible(true);
        } else {
            jPanelRaiz.setVisible(false);
            jPanelLuz.setVisible(false);
        }
    }//GEN-LAST:event_luzActionPerformed

    private void aquecedorAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aquecedorAguaActionPerformed
        if (jPanelRaiz.isVisible() == false) {
            jPanelRaiz.setVisible(true);
            jPanelAquecedor.setVisible(true);
        } else {
            jPanelRaiz.setVisible(false);
            jPanelAquecedor.setVisible(false);
        }
    }//GEN-LAST:event_aquecedorAguaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void intensidadeLuz8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidadeLuz8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidadeLuz8ActionPerformed

    private void inputIntensidadeLuz9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIntensidadeLuz9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIntensidadeLuz9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void intensidadeLuz9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidadeLuz9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidadeLuz9ActionPerformed

    private void inputIntensidadeLuz10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIntensidadeLuz10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIntensidadeLuz10ActionPerformed

    private void intensidadeLuz10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidadeLuz10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidadeLuz10ActionPerformed

    private void inputIntensidadeLuz4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIntensidadeLuz4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIntensidadeLuz4ActionPerformed

    private void intensidadeLuz11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidadeLuz11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intensidadeLuz11ActionPerformed

    private void inputIntensidadeLuz11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIntensidadeLuz11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIntensidadeLuz11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aquecedorAgua;
    private javax.swing.JButton arCondicionado;
    private javax.swing.JToggleButton bntLigarDesligarLuz1;
    private javax.swing.JToggleButton bntLigarDesligarLuz10;
    private javax.swing.JToggleButton bntLigarDesligarLuz11;
    private javax.swing.JToggleButton bntLigarDesligarLuz2;
    private javax.swing.JToggleButton bntLigarDesligarLuz5;
    private javax.swing.JToggleButton bntLigarDesligarLuz8;
    private javax.swing.JToggleButton bntLigarDesligarLuz9;
    private javax.swing.JTextField inputIntensidadeLuz1;
    private javax.swing.JTextField inputIntensidadeLuz10;
    private javax.swing.JTextField inputIntensidadeLuz11;
    private javax.swing.JTextField inputIntensidadeLuz2;
    private javax.swing.JTextField inputIntensidadeLuz4;
    private javax.swing.JTextField inputIntensidadeLuz5;
    private javax.swing.JTextField inputIntensidadeLuz9;
    private javax.swing.JToggleButton intensidadeLuz1;
    private javax.swing.JToggleButton intensidadeLuz10;
    private javax.swing.JToggleButton intensidadeLuz11;
    private javax.swing.JToggleButton intensidadeLuz2;
    private javax.swing.JToggleButton intensidadeLuz5;
    private javax.swing.JToggleButton intensidadeLuz8;
    private javax.swing.JToggleButton intensidadeLuz9;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAquecedor;
    private javax.swing.JPanel jPanelAr;
    private javax.swing.JPanel jPanelAr2;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLuz;
    private javax.swing.JPanel jPanelLuz1;
    private javax.swing.JPanel jPanelLuz2;
    private javax.swing.JPanel jPanelPorta;
    private javax.swing.JPanel jPanelRaiz;
    private javax.swing.JPanel jPanelTv;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelIntensidadeLuz1;
    private javax.swing.JLabel labelIntensidadeLuz2;
    private javax.swing.JLabel labelIntensidadeLuz5;
    private javax.swing.JLabel labelLigadoDesligadoLuz1;
    private javax.swing.JLabel labelLigadoDesligadoLuz10;
    private javax.swing.JLabel labelLigadoDesligadoLuz2;
    private javax.swing.JLabel labelLigadoDesligadoLuz5;
    private javax.swing.JButton luz;
    private javax.swing.JButton porta;
    private javax.swing.JButton televisao;
    // End of variables declaration//GEN-END:variables
}
